# Generated by Django 5.1.7 on 2025-05-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_firstname', models.CharField(max_length=50)),
                ('s_lastname', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phonenumber', models.IntegerField()),
                ('s_guardianphonenumber', models.IntegerField()),
                ('s_qualification', models.TextField()),
            ],
        ),
    ]
