# Generated by Django 5.1.7 on 2025-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbstudent',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_profilepicture', models.ImageField(upload_to='')),
                ('s_firstname', models.CharField(max_length=50)),
                ('s_lastname', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phonenumber', models.IntegerField()),
                ('s_guardianphonenumber', models.IntegerField()),
                ('s_qualification', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
