# Generated by Django 5.1.7 on 2025-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_dbstudent_delete_admin_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbstudent1',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_profilepicture', models.ImageField(upload_to='')),
                ('s_firstname', models.CharField(max_length=50)),
                ('s_lastname', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phonenumber', models.IntegerField()),
                ('s_guardianphonenumber', models.IntegerField()),
                ('s_qualification', models.TextField()),
                ('s_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('s_password', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='dbstudent',
        ),
    ]
