# Generated by Django 5.1.7 on 2025-05-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_dbstudent1_delete_dbstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_email', models.EmailField(max_length=254, unique=True)),
                ('t_password', models.CharField(max_length=50)),
            ],
        ),
    ]
