# Generated by Django 5.1.7 on 2025-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_dbteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbteacher1',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_email', models.EmailField(max_length=254, unique=True)),
                ('t_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='dbteacher',
        ),
    ]
