# Generated by Django 5.1.7 on 2025-05-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_dbteacher1_delete_dbteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstudent1',
            name='s_guardianphonenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dbstudent1',
            name='s_phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
